<?php

return [
    'color' => ['required', 'regex:/^#(?:[0-9a-fA-F]{3}){1,2}$/'],
    'color_secondary' => ['required', 'regex:/^#(?:[0-9a-fA-F]{3}){1,2}$/'],
    'surface_color' => ['required', 'regex:/^#(?:[0-9a-fA-F]{3}){1,2}$/'],
    'background_color' => ['required', 'regex:/^#(?:[0-9a-fA-F]{3}){1,2}$/'],
    'hero_background' => ['nullable', 'url', 'max:255'],
    'hero_icon' => ['nullable', 'url', 'max:255'],
    'server_ip' => ['nullable', 'string', 'max:120'],
    'hero_title' => ['required', 'string', 'max:120'],
    'hero_subtitle' => ['nullable', 'string', 'max:255'],
    'discord_url' => ['nullable', 'url', 'max:255'],
    'footer_text' => ['nullable', 'string', 'max:255'],
    'showcase_video_url' => ['nullable', 'url', 'max:255'],
    'showcase_video_title' => ['nullable', 'string', 'max:120'],
    'showcase_video_text' => ['nullable', 'string', 'max:255'],
    'nav_position' => ['required', 'in:top,side'],
    'loading_screen_enabled' => ['nullable', 'boolean'],
    'loading_screen_style' => ['required', 'in:spinner,bars,cinematic'],
    'page_transition' => ['required', 'in:none,fade,slide'],
    'animation_level' => ['required', 'in:off,subtle,full,cinematic'],
    'hero_animation' => ['required', 'in:none,float,zoom'],
    'enable_3d_tilt' => ['nullable', 'boolean'],
    'enable_parallax' => ['nullable', 'boolean'],
    'enable_glow' => ['nullable', 'boolean'],
    'enable_background_grid' => ['nullable', 'boolean'],
    'enable_cinematic_intro' => ['nullable', 'boolean'],
    'modes_title' => ['nullable', 'string', 'max:80'],
    'mode_1_name' => ['nullable', 'string', 'max:40'],
    'mode_1_url' => ['nullable', 'string', 'max:255'],
    'mode_2_name' => ['nullable', 'string', 'max:40'],
    'mode_2_url' => ['nullable', 'string', 'max:255'],
    'mode_3_name' => ['nullable', 'string', 'max:40'],
    'mode_3_url' => ['nullable', 'string', 'max:255'],
    'mode_4_name' => ['nullable', 'string', 'max:40'],
    'mode_4_url' => ['nullable', 'string', 'max:255'],
];
